name: Compile Material Bin
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Download MaterialBinTool
        run: |
          wget https://github.com -O MaterialBinTool.jar

      - name: Download Shaderc for Linux
        run: |
          wget https://github.com -O shaderc
          chmod +x shaderc

      - name: Compile Shader
        run: |
          java -jar MaterialBinTool.jar -s ./shaderc -c ./src

      - name: Upload Material Bin Result
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Materials
          path: src/**/*.material.bin
          
